config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get '/category/:title', to: 'static_pages#category'

  get 'cart/index'

  resources :items
  #get 'static_pages/home'
  root 'static_pages#home'
  #get 'static_pages/help'
  
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  
  get '/login', to: 'user#login'
  get '/logout', to: 'user#logout'
  
  
  get '/clearcart', to: 'cart#clearCart'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'
  
  root :to => 'site#home'
  
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  post '/search' => 'items#search'

  resources :orders do 
    resources:orderitems
  end
  
  devise_for :users do 
    resources :orders
  end
  get '/aboutSend/:id' => 'static_pages#aboutSend'
  
  get '/checkout' => 'cart#createOrder'
  get '/paid/:id' => 'static_pages#paid'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_categories.html.erb
<% @categories.each do |category| %>
       <div class="itemhols">
           <p><%= category.title %></p>
           <%= link_to (image_tag category.image, :class=>"itemholsIm"), category %>
           <p><%= category.description %></p>
         </div>
        <p><a href="/category/<%= category.title %>" class="button"><%= category.title %></a></p>

    <% end %>

app/views/layouts/_header.html.erb
   <header class="headSec">
      <h1>Ailbhe's food and beverages store</h1>
      
      
    <ul>
        
        <li><%= link_to "Home",  "/" %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log In", login_path %></li>
        <li><%= link_to "Log Out", logout_path %></li>
        <li><%= link_to "View Cart", "/cart" %></li>
        <li><%= link_to "View Orders", orders_path  %></li>

     </ul>
      
    </header>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "F&BStore" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <header class="headSec">
      <h1>La Petiza food shop</h1>
      
      <ul>
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Item", "/items" %></li>
        <li><%= link_to "View Cart", "/cart" %></li>
  
       <% if user_signed_in? %>
                 <li><a href="#">Hi <%= current_user.email %></a></li>
                 <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                 <li><%= link_to "View Orders", orders_path  %></li>
                 <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
                 <li><%= link_to 'Register', new_user_registration_path %></li> 
                 <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>

        <% if session[:login] == 1 %> 
        <li><%= link_to "Admin Logout", logout_path %></li>
        <% else %>
        
        <li><%= link_to "Admin Login", login_path %></li>
        <% end %>
      </ul>
  


    </header>

    <div class="container">
    <%= yield %>
    <%=render 'layouts/search'%>
    </div>

<footer class="foot">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<a href="#" class="fa fa-facebook"></a>
<a href="#" class="fa fa-twitter"></a>
<a href="#" class="fa fa-linkedin"></a>
<a href="#" class="fa fa-youtube"></a>
<a href="#" class="fa fa-instagram"></a>


</footer>
  </body>
</html>